# Generated by Django 3.2.9 on 2021-11-28 03:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(max_length=1000)),
                ('time', models.DateTimeField(default=datetime.datetime(2021, 11, 28, 10, 30, 37, 187501))),
            ],
        ),
    ]
